### ISSUE TITLE
Can you provide access to Coding_RawCount_AT_BT.txt

### ISSUE THREAD

**Issue by raghvendra5688** [neogilab/CCHF-Turkey#1]
The raw fastq files are provided but is there a possibility to provide access to the file Coding_RawCount_AT_BT.txt used in the code?

**Comment by neogilab** [comment]
Hi,
Please share your mail ID. I will mail you the the file.

**Comment by raghvendra5688** [comment]
My mail id is ***@***.***

Thanks a lot in advance.

With Regards,
Raghvendra

**Comment by neogilab** [comment]
hi,
the email ID is not visible.

**Comment by raghvendra5688** [comment]
My email id is raghvendra5688@gmail.com

**Comment by neogilab** [comment]
mailed u the count table. Thank you for your interest in our study.
